#include <stdbool.h>
// Mod taps
#undef TAPPING_TERM
#define TAPPING_TERM 190
#undef MIRYOKU_KLUDGE_THUMBCOMBOS

#undef QUICK_TAP_TERM
#define QUICK_TAP_TERM 80

// Combos
#define COMBO_COUNT 3
#define COMBO_TERM 20
#define EXTRA_SHORT_COMBOS

// Detect keyboard better
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 2000
#define SPLIT_USB_TIMEOUT_POLL 10
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WATCHDOG_TIMEOUT 3000

#ifdef POINTING_DEVICE_ENABLE
    #define CIRQUE_PINNACLE_TAP_ENABLE
    #define DILEMMA_MINIMUM_DEFAULT_DPI 150
    #define DILEMMA_AUTO_POINTER_LAYER_TRIGGER_ENABLE
    #define POINTING_DEVICE_AUTO_MOUSE_ENABLE
    #define AUTO_MOUSE_TIME 350
    #define AUTO_MOUSE_THRESHOLD 0
    #define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#endif
